services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "9000:80"
    restart: unless-stopped

# docker compose up --build 